name: phi35v
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.0
  - pip:
      - ipython==8.18.1
      - typed-argument-parser==1.10.1
      - numpy==1.26.4
      - datasets==2.21.0
      - Pillow==10.4.0
      - openai==1.41.1
