name: visonlyqa
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.0
  - pip:
      - ipython==8.18.1
      - typed-argument-parser==1.10.1
      - datasets==2.21.0
      - numpy==1.26.4
      - Pillow==10.4.0
      - gspread==6.1.2
      - PyDrive==1.3.1
      - gspread-formatting==1.2.0
      - openai==1.41.1
      - anthropic==0.37.1
      - google-generativeai==0.8.3
      - gdown==5.2.0
      - tensorboard==2.17.1
      - matplotlib==3.9.2
      - scipy==1.14.1
